### ISSUE TITLE
使用该SDK必须获取用户手机号的权限吗

### ISSUE THREAD

**Issue by HarrisonQi** [adtalos/flutter_xy_plugin#10]
我不希望新用户安装时提示"需获取手机号、通话记录"的权限, 请问可以关闭吗?

**Comment by andot** [comment]
https://github.com/adtalos/flutter_xy_plugin/blob/600bbe6908234ad4abcebfbe2b93728eb2e73ffa/android/src/main/java/com/adtalos/flutter_xy_plugin/FlutterXyPlugin.java#L62

把这一句删掉就可以了。这一句是用来弹出请求权限窗口的，你可以使用更友好的方式来获取这些权限。这里面有些权限不获取，可能得不到获取广告所需的设备信息，比如 imei 之类的，这样的话，服务器可能会不返回广告。

**Comment by HarrisonQi** [comment]
好的, 成功了. 非常感谢😃

**Comment by andot** [comment]
不客气😁
