### ISSUE TITLE
在激励视频广告时点击下载,闪退

### ISSUE THREAD

**Issue by aluo44** [adtalos/flutter_xy_plugin#13]
接入后: 
在激励视频广告时点击下载,APP闪退

**Comment by andot** [comment]
下载广告需要存储读取和写入的权限，是不是权限没有开启造成的

**Comment by aluo44** [comment]
不是, 我刚试了下, 保存图片成功了, 点击下载还是闪退

**Comment by andot** [comment]
有什么错误信息吗？

**Comment by aluo44** [comment]
我用AS拿到的信息
`W/Settings( 4980): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor( 4980): User setup is finished.
D/ziparchive( 4980): Zip: EOCD not found, /storage/emulated/0/Android/data/com.bfbvideotok.app/files/Download/detail.htm is not zip
E/bfbvideotok.ap( 4980): Failed to open APK '/storage/emulated/0/Android/data/com.bfbvideotok.app/files/Download/detail.htm' Invalid file
D/TextView( 4980): get Display Panel Type is : 0
I/DownloadHelper( 4980): Download start
D/TrackReport( 4980): TrackType: download_begin_trackers
D/TrackReport( 4980): https://api.mobrtb.com/tracker?request_id=bt30pso6lh7ot0pt7mig&log_event_type=13
D/TrackReport( 4980): TrackType: click_trackers
D/TrackReport( 4980): https://api.mobrtb.com/tracker?request_id=bt30pso6lh7ot0pt7mig&log_event_type=8
W/InputMethodManager( 4980): startInputReason = 4
V/Logging ( 4980): 201:Created
V/Logging ( 4980): 201:Created
D/OpenGLRenderer( 4980):   HWUI Binary is  enabled
D/OpenGLRenderer( 4980): disableOutlineDraw is true
D/TrackReport( 4980): 200:OK
D/mali_winsys( 4980): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/SpannableStringBuilder( 4980): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder( 4980): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
V/Logging ( 4980): 201:Created
D/OpenGLRenderer( 4980):   HWUI Binary is  enabled
D/OpenGLRenderer( 4980): disableOutlineDraw is true
V/Logging ( 4980): 201:Created
D/TrackReport( 4980): 200:OK
V/Logging ( 4980): 201:Created
V/Logging ( 4980): 201:Created
V/Logging ( 4980): 201:Created
I/DownloadHelper( 4980): Download success
D/TrackReport( 4980): TrackType: download_ended_trackers
D/TrackReport( 4980): https://api.mobrtb.com/tracker?request_id=bt30pso6lh7ot0pt7mig&log_event_type=14
D/ziparchive( 4980): Zip: EOCD not found, /storage/emulated/0/Android/data/com.bfbvideotok.app/files/Download/detail-2.htm is not zip
E/bfbvideotok.ap( 4980): Failed to open APK '/storage/emulated/0/Android/data/com.bfbvideotok.app/files/Download/detail-2.htm' Invalid file
D/AndroidRuntime( 4980): Shutting down VM
E/AndroidRuntime( 4980): FATAL EXCEPTION: main
E/AndroidRuntime( 4980): Process: com.bfbvideotok.app, PID: 4980
E/AndroidRuntime( 4980): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.bfbvideotok.app (has extras) } in com.example.r_upgrade.common.UpgradeManager$3@69c3243
E/AndroidRuntime( 4980): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1546)
E/AndroidRuntime( 4980): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime( 4980): 	at android.os.Handler.handleCallback(Handler.java:907)
E/AndroidRuntime( 4980): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 4980): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime( 4980): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime( 4980): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4980): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime( 4980): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AndroidRuntime( 4980): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
E/AndroidRuntime( 4980): 	at com.example.r_upgrade.common.UpgradeManager$3.onReceive(UpgradeManager.java:314)
E/AndroidRuntime( 4980): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
E/AndroidRuntime( 4980): 	... 8 more
E/CrashHandler( 4980): uncaughtException: main Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.bfbvideotok.app (has extras) } in com.example.r_upgrade.common.UpgradeManager$3@69c3243
E/CrashHandler( 4980): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.bfbvideotok.app (has extras) } in com.example.r_upgrade.common.UpgradeManager$3@69c3243
E/CrashHandler( 4980): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1546)
E/CrashHandler( 4980): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/CrashHandler( 4980): 	at android.os.Handler.handleCallback(Handler.java:907)
E/CrashHandler( 4980): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/CrashHandler( 4980): 	at android.os.Looper.loop(Looper.java:216)
E/CrashHandler( 4980): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/CrashHandler( 4980): 	at java.lang.reflect.Method.invoke(Native Method)
E/CrashHandler( 4980): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/CrashHandler( 4980): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/CrashHandler( 4980): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
E/CrashHandler( 4980): 	at com.example.r_upgrade.common.UpgradeManager$3.onReceive(UpgradeManager.java:314)
E/CrashHandler( 4980): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
E/CrashHandler( 4980): 	... 8 more
V/Logging ( 4980): 201:Created
D/TrackReport( 4980): 200:OK
V/Logging ( 4980): 201:Created
V/Logging ( 4980): 201:Created
V/Logging ( 4980): 201:Created
V/Logging ( 4980): 201:Created
I/Process ( 4980): Sending signal. PID: 4980 SIG: 9
Lost connection to device.
`

**Comment by andot** [comment]
看起来是下载完成事件被别的代码接管了，你是不是用了什么别的接管了。com.example.r_upgrade.common.UpgradeManager 这段代码不是我们广告 sdk 里面的。

**Comment by aluo44** [comment]
插件有冲突, 我刚从AS返回的信息试了下, 里面有个r_upgrade插件, 是用来升级的. 去掉后就不闪退了

**Comment by andot** [comment]
嗯，是这个问题。

**Comment by aluo44** [comment]
但是这个问题要如何解决, 升级是肯定需要的

**Comment by andot** [comment]
那个升级的代码看上去有错误，这个跟这个广告 sdk 没什么关系。你找个没错误的升级插件试试看。

**Comment by aluo44** [comment]
呃...或者换一种角度想, 让下载的是不是基本都是APK, 如果是APK是不是就应该没什么问题了?

**Comment by andot** [comment]
嗯，广告 sdk 里面下载的应该都是 apk，虽然下载连接里面的扩展名不一定都是 apk。

**Comment by aluo44** [comment]
好的  谢谢

**Comment by andot** [comment]
不客气
