### ISSUE TITLE
请问必须要公司资质吗

### ISSUE THREAD

**Issue by saviourdog** [adtalos/flutter_xy_plugin#16]

**Comment by andot** [comment]
这个你可以加我们媒介的微信问一下，我只是个技术，这方面的问题我不是很清楚。我个人觉得个人开发者应该也可以吧，哈哈。

**Comment by saviourdog** [comment]
@andot 微信多少呢,谢谢

**Comment by andot** [comment]
你留个联系方式，我们媒介会加你的。

**Comment by saviourdog** [comment]
qq1690364680,谢谢!

**Comment by andot** [comment]
不客气

**Comment by supermebing** [comment]
> qq1690364680,谢谢!

是否需要公司资质

**Comment by andot** [comment]
> > qq1690364680,谢谢!
> 
> 是否需要公司资质

不需要的，直接加我们媒介的微信就可以了：xloooooo
